# Generated by Django 4.2.23 on 2025-07-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
