NAME_DISPLAY_LENGTH = 20

USERNAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 128
USERNAME_REGEX = r'^[\w.@+-]+\Z'
USERNAME_FORBIDDEN = 'me'
EMAIL_MAX_LENGTH = 254
NAME_MAX_LENGTH = 150
TAG_MAX_LENGTH = 32
SLUG_MAX_LENGTH = 32
SLUG_REGEX = r'[-a-zA-Z0-9_]+$'