NAME_DISPLAY_LENGTH = 20

USERNAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 128
USERNAME_REGEX = r'^[\w.@+-]+\Z'
USERNAME_FORBIDDEN = 'me'
EMAIL_MAX_LENGTH = 254
NAME_MAX_LENGTH = 150
RECIPE_NAME_MAX_LENGTH = 256
RECIPE_DISPLAY_WORDS_LENGTH = 5
TAG_MAX_LENGTH = 32
SLUG_MAX_LENGTH = 32
SLUG_REGEX = r'[-a-zA-Z0-9_]+$'
INGREDIENT_MAX_LENGTH = 128
UNIT_OF_MEASURE_MAX_LENGTH = 64