# version: '3.8'

volumes:
  pg_data:
  static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: kkleinikov/foodgram-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: kkleinikov/foodgram-frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/app/build

  gateway:
    image: kkleinikov/foodgram-gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media/
      - frontend_static:/frontend_static
    depends_on:
      - backend
      - frontend