NAME_DISPLAY_LENGTH = 20
NAME_MAX_LENGTH = 150
TEXT_FIELDS_DISPLAY_LENGTH = 20

USERNAME_MAX_LENGTH = 150
USERNAME_REGEX = r'^[\w.@+-]+\Z'
EMAIL_MAX_LENGTH = 254

RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME = 1  # в минутах

TAG_MAX_LENGTH = 32
SLUG_MAX_LENGTH = 32

INGREDIENT_MAX_LENGTH = 128
UNIT_OF_MEASURE_MAX_LENGTH = 64
MIN_INGREDIENT_AMOUNT = 1
