# Generated by Django 4.2.23 on 2025-07-13 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Слаг может содержать только буквы, цифры, дефисы и нижние подчеркивания', regex='[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
