# Generated by Django 4.2.23 on 2025-07-13 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тега (до 32 символов)', max_length=32, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Слаг может содержать только буквы, цифры, дефисы и нижние подчеркивания', regex='[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
