# Generated by Django 4.2.23 on 2025-07-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_foodgramuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='foodgram_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='foodgram_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
