# Generated by Django 4.2.23 on 2025-07-21 19:03

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_foodgramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Длина имени пользователя не может превышать 150 символов'}, max_length=150, unique=True, validators=[api.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
